version: '2'
services:
  backend:
    container_name: backend-server
    image: adeledev/bus-depot-backend:latest
    ports:
      - "8080:8080"
    volumes:
      - db:/data
  frontend:
    container_name: frontend-server
    image: adeledev/bus-depot-frontend:latest
    ports:
      - "3000:80"
volumes:
  db: